### ISSUE TITLE
metabolic summary file

### ISSUE THREAD

**Issue by eddykay310** [cruizperez/MicrobeAnnotator#22]
Hi @cruizperez 

Please I would like to find out if there is an explanation for getting the same set of genes in the metabolic_summary__module_completeness tab file after running the analysis. I used two different fasta files, one is a whole genome and the other is a small subset of genes but got the same output.

Thank you

**Comment by cruizperez** [comment]
Hi! Could you please tell me how did you run the samples? And also if you can sharr the output that would be awesome. Thanks!

**Comment by eddykay310** [comment]
Hi,

This is the command i used for both files

microbeannotator -i /home/Mu.fna -d /home/microbeannotater/MicrobeAnnotator_DB -o output -m diamond -p 2 -t 3 --light --refine

For the output files can I do that via email?

Thanks

**Comment by cruizperez** [comment]
Let me see if I understand this correctly. The Mu.fna file has the proteins from both genomes?

**Comment by eddykay310** [comment]
Used a nucleic acid fasta as input in both cases instead of their proteins. Thanks for drawing my attention.
