### ISSUE TITLE
Conflicts at installing

### ISSUE THREAD

**Issue by mrgambero** [cruizperez/MicrobeAnnotator#39]
Hello, 
I am trying to install microbe annotator using conda, but I get the following error messages connected to 

COMMAND
(base) gabri@x86_64-apple-darwin13 Error_corrected % conda create -n microbeannotator python=3.7 pip microbeannotator=2.0.5

OUTPUT
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
microbeannotator=2.0.5 -> attrs==20.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6']
pip -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
microbeannotator=2.0.5 -> python[version='>=3.7,<3.8.0a0']
pip -> wheel -> python

Package certifi conflicts for:
pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
microbeannotator=2.0.5 -> requests==2.25.1 -> certifi[version='>=2017.4.17']

Package ca-certificates conflicts for:
python=3.7 -> openssl[version='>=1.1.1k,<1.1.2a'] -> ca-certificates
pip -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates

I do not know how to solve this issue, any idea?

Thanks for your work!

Gabri

**Comment by rotheconrad** [comment]
leave pip out. Once you create the conda environment, activate the environment, and you can install additional software using conda install instead of pip.

**Comment by mrgambero** [comment]
Thank you, I tried and now it gives me these errors:


Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
microbeannotator=2.0.5 -> python[version='>=3.7,<3.8.0a0']
python=3.7
microbeannotator=2.0.5 -> attrs==20.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6']

**Comment by rotheconrad** [comment]
What if you try without specifying python?

conda create -n microbeannotator microbeannotator=2.0.5

**Comment by mrgambero** [comment]
It works now,
I am sorry it was my mistake, I did not install the channels bioconda and conda-forge because I thought they were already installed since I used them all the time with -c. 

Now that they are all installed it works!
I am sorry to bother, but thanks a lot for your fast replies!!!

Gabri
