### ISSUE TITLE
Error during DB building

### ISSUE THREAD

**Issue by pvstodghill** [cruizperez/MicrobeAnnotator#4]
The "light" version produced very informative results for several genomes that we are working with. Hoping to get a more detailed idea of the pathways present in the various strains, I tried to download and building the "full" databases. Unfortunately, the download/build failed, during step 2 (I think!). I restarted from the beginning of step 2 and got the same error message,

~~~
(microbeannotator) $ microbeannotator_db_builder -d ~/scratch/microbeannotator -m blast -t $(nproc) --step 2
Parsing swissprot and trembl annotation data...
Done!
Parsing refseq annotation data...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/site-packages/independent_scripts/refseq_genbank_parser.py", line 41, in table_creator
    for record in SeqIO.parse(uncompressed_genbank, "genbank"):
  File "/home/ps27/.local/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/ps27/.local/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/ps27/.local/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 466, in feed
    self._feed_header_lines(consumer, self.parse_header())
  File "/home/ps27/.local/lib/python3.7/site-packages/Bio/GenBank/Scanner.py", line 1802, in _feed_header_lines
    structured_comment_key
KeyError: 'Assembly-Data'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ps27/.conda/envs/microbeannotator/bin/microbeannotator_db_builder", line 11, in <module>
    sys.exit(main())
  File "/home/ps27/.conda/envs/microbeannotator/bin/microbeannotator_db_builder.py", line 206, in main
    db_duilder(directory, method, light, threads, step, aspera, keep, bin_path)
  File "/home/ps27/.conda/envs/microbeannotator/bin/microbeannotator_db_builder.py", line 89, in db_duilder
    temp_table_list = refseq_genbank_parser.table_generator_worker(genbank_files, threads)
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/site-packages/independent_scripts/refseq_genbank_parser.py", line 90, in table_generator_worker
    temp_table_list = pool.map(table_creator, genbank_list)
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ps27/.conda/envs/microbeannotator/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: 'Assembly-Data'
(microbeannotator) $ 
~~~

Based on the error message, I suspect that one of the downloaded files is incomplete/corrupt. Is this correct? If so, is there a way to rerun step 1 (the download) without re-downloading all of the files (which takes a alot of time/bandwidth)?

Thanks.

**Comment by pvstodghill** [comment]
I forgot to mention: I installed MicrobeAnnotator from your conda channel yesterday.

~~~~
conda config --add channels cruizperez
conda create -n microbeannotator microbeannotator [...]
conda activate microbeannotator
~~~~

~~~
(microbeannotator) $ microbeannotator --version
MicrobeAnnotator v1.0.4
(microbeannotator) $ 
~~~

**Comment by cruizperez** [comment]
Hi @pvstodghill !
Thanks for using our software! Indeed it seems there is a problem with the genbank files downloaded from RefSeq. If you are using Aspera Connect to download the data, there might be a way to only download the genbank files. What you should do is run an independent script located in the libraries used by MicrobeAnnotator to only download these files in the folder that microbeannotator_db_builder expects them. The script should be in the following location within your Anaconda installation:
[Path to Anaconda]/envs/microbeannotator/lib/python3.7/site-packages/independent_scripts/refseq_data_downloader.py
In your case you could run it as:
~~~
python [Path to Anaconda]/envs/microbeannotator/lib/python3.7/site-packages/independent_scripts/refseq_data_downloader.py -f ~/scratch/microbeannotator/02.temp_genbank --genbank
~~~
This should download only the genbank files in the 02.temp_genbank folder.
If you are not using Aspera Connect then I'm afraid you must re-run from step one. However, if you have a couple of days, I can update this script to allow users to download the data without Aspera.

**Comment by pvstodghill** [comment]
I tried the command that you suggested. I think perhaps that it should have been `-f ~/scratch/microbeannotator/` instead of `-f ~/scratch/microbeannotator/02.temp_genbank`, as the result was a new directory, `~/scratch/microbeannotator/02.temp_genbank/02.temp_genbank`. At that point everything (by which I mean, "I") became confused. I've deleted the entire  `~/scratch/microbeannotator/` and I'm starting over.

Now that I understand what went wrong, I would like to turn the bug report into several feature requests:

1) Could MicrobeAnnotator produce a more informative error message to when the downloaded files are corrupt?
2) Would it be possible to verify/validate all of the downloaded files before moving to the next step?
3) Could an option be added to restart/resume the download step?

Thanks again for making this package available to the public. We are finding the "light" results very helpful.

**Comment by cruizperez** [comment]
Hi Paul!
Thanks for trying out my solution! Sorry I missed the output folder, but I hope it is working now. I have planned to incorporate your requests in a future release as follows:
- MicrobeAnnotator will check the integrity of the files and will attempt a re-download if they are found to be corrupt.
- This of course includes verifying each file, so in theory every file should be correctly downloaded before the next step.
- I am already working on adding more "steps" so the user has the option to resume downloads from the data they are missing, e.g. start from the metadata download, skipping the proteins.
I will leave this thread open until I incorporate these changes to let you know when they are ready!

Carlos

**Comment by cruizperez** [comment]
An update on this. MicrobeAnnotator will have more steps in the database building pipeline so it can restart from a failed step or if the user needs, just run one of the steps.
I will be working on the verification of downloaded files in the future.
