### ISSUE TITLE
Typo in --method_bin flag descriptor

### ISSUE THREAD

**Issue by RVTrexler** [cruizperez/MicrobeAnnotator#5]
Hello,

I believe there is a typo in the descriptor for the `--method_bin` flag when running `microbeannotator -h`. I think Line 63 in microbeannotator.py should be changed to refer to the method binaries, not the KOFamscan binaries.

Currently `microbeannotator -h` outputs the following:

"--method_bin METHOD_BIN
                        Directory where KOFamscan binaries are located. By default assumes it is in PATH."

Thanks for your tool, I'm very excited to use it.

Best,

Ryan

**Comment by cruizperez** [comment]
Thank you for using our program! I have fixed this typo.
