### ISSUE TITLE
kofam_scan error.

### ISSUE THREAD

**Issue by hh1985** [cruizperez/MicrobeAnnotator#8]
After installation of kofam_scan, I got following error:

```
./exec_annotation -h
./exec_annotation: /data/public/kofamscan/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:175: multiple assignment in conditional (SyntaxError)
```

It seems there's ruby syntax error.

**Comment by cruizperez** [comment]
Hi, 
I am actually not sure about this error. MicrobeAnnotator uses kofamscan for the first step but this error appears to be related to kofamscan itself. Maybe you can track this error or a similar one in their GitHub site? https://github.com/takaram/kofam_scan
